"""Remove is_system_generated column from LoanRepayment

Revision ID: 0065902bb63e
Revises: a5b5385b8430
Create Date: 2025-06-05 10:43:28.039987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0065902bb63e'
down_revision = 'a5b5385b8430'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_repayments', schema=None) as batch_op:
        batch_op.drop_column('is_system_generated')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_repayments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_system_generated', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
