"""Add Google Drive fields to Company

Revision ID: 1a6b77377c1c
Revises: b5f858442b9a
Create Date: 2025-09-01 12:53:18.857505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a6b77377c1c'
down_revision = 'b5f858442b9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drive_token', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('drive_refresh_token', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('drive_token_uri', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('drive_client_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('drive_client_secret', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('drive_client_secret')
        batch_op.drop_column('drive_client_id')
        batch_op.drop_column('drive_token_uri')
        batch_op.drop_column('drive_refresh_token')
        batch_op.drop_column('drive_token')

    # ### end Alembic commands ###
