"""Split loan_duration into value and unit

Revision ID: 3feece28916f
Revises: e9fc511bfbfd
Create Date: 2025-05-29 14:34:10.536133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3feece28916f'
down_revision = 'e9fc511bfbfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_duration_value', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('loan_duration_unit', sa.String(length=10), nullable=True))
        batch_op.drop_column('loan_duration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_duration', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('loan_duration_unit')
        batch_op.drop_column('loan_duration_value')

    # ### end Alembic commands ###
