"""Rename amount to payment in ledger_entries

Revision ID: 4d328d36d533
Revises: 28cf42a4fbed
Create Date: 2025-12-24 00:47:29.782437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d328d36d533'
down_revision = '28cf42a4fbed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
