"""Clean up penalty to cumulative_interest columns

Revision ID: a5b5385b8430
Revises: d9ac523a8c81
Create Date: 2025-06-03 13:13:02.638132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5b5385b8430'
down_revision = 'd9ac523a8c81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_column('cumulative_interest_balance')
        batch_op.drop_column('cumulative_interest')

    with op.batch_alter_table('loan_repayments', schema=None) as batch_op:
        batch_op.drop_column('cumulative_interest_paid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_repayments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cumulative_interest_paid', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cumulative_interest', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cumulative_interest_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
