"""Add ledger_entries table and update loan_repayment date_paid

Revision ID: ad934029dbb9
Revises: 3feece28916f
Create Date: 2025-05-30 13:50:41.467901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad934029dbb9'
down_revision = '3feece28916f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('particulars', sa.String(length=255), nullable=False),
    sa.Column('principal', sa.Float(), nullable=True),
    sa.Column('interest', sa.Float(), nullable=True),
    sa.Column('penalty', sa.Float(), nullable=True),
    sa.Column('principal_balance', sa.Float(), nullable=True),
    sa.Column('interest_balance', sa.Float(), nullable=True),
    sa.Column('penalty_balance', sa.Float(), nullable=True),
    sa.Column('running_balance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loan_repayments', schema=None) as batch_op:
        batch_op.alter_column('date_paid',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_repayments', schema=None) as batch_op:
        batch_op.alter_column('date_paid',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    op.drop_table('ledger_entries')
    # ### end Alembic commands ###
