"""Add cumulative interest fields to LedgerEntry

Revision ID: b5f858442b9a
Revises: 930ae28209a4
Create Date: 2025-06-23 17:42:46.498656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5f858442b9a'
down_revision = '930ae28209a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cumulative_interest', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('cumulative_interest_balance', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_column('cumulative_interest_balance')
        batch_op.drop_column('cumulative_interest')

    # ### end Alembic commands ###
