"""Add cumulative_interest to LoanRepayment

Revision ID: ba08ae0f4032
Revises: 62404cf5d698
Create Date: 2025-06-23 12:53:40.447347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba08ae0f4032'
down_revision = '62404cf5d698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_repayments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cumulative_interest', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_repayments', schema=None) as batch_op:
        batch_op.drop_column('cumulative_interest')

    # ### end Alembic commands ###
