"""Add cumulative_interest_paid and is_system_generated to LoanRepayment

Revision ID: d9ac523a8c81
Revises: 2f87b5c9bd44
Create Date: 2025-06-02 22:18:51.891247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9ac523a8c81'
down_revision = '2f87b5c9bd44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_repayments', schema=None) as batch_op:
        batch_op.alter_column('cumulative_interest_paid',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_repayments', schema=None) as batch_op:
        batch_op.alter_column('cumulative_interest_paid',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    # ### end Alembic commands ###
