"""Add approval_status to loans

Revision ID: e9fc511bfbfd
Revises: fa5ccb7cd517
Create Date: 2025-05-28 15:44:10.432327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9fc511bfbfd'
down_revision = 'fa5ccb7cd517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_column('approval_status')

    # ### end Alembic commands ###
